name: "Hello World"
description: "Greet someone and record the time"
inputs:
  who-to-greet: # id of input
    description: "Who to greet"
    required: true
    default: "World"
  example-param:
    description: "An example parameter"
  ms-teams-webhook-uri:
    description: "Microsoft Teams Webhook URI"
    required: true
outputs:
  time: # id  of output
    description: "The time we greeted you"
runs:
  using: "node16"
  main: index.js
