name: "MsTeams Notifier Direct"

on:
  push:
    branches: [main]

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/github-script@v6
        with:
          script: |
            const getRelatedPr = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: process.env.GITHUB_SHA
             })

             console.log(getRelatedPr,context,process.env)

            const prNumber = getRelatedPr.data.length > 0 ? getRelatedPr.data[0].number : undefined;
            if (prNumber === undefined) {
              console.log("No matching PR number")
              exit(1)
            }
            const [title, message] = context.payload.head_commit.message.split("\n")

            const info = {
                prNumber,
                prUrl: getRelatedPr.data[0]._links.html.href,
                title,
                message,
                previewUrl: `https://deploy-preview-${prNumber}--airup-webshop-dev1.netlify.app`,
                commitUrl: context.payload.head_commit.url,
                pusher: context.payload.pusher.name,
                author: context.payload.head_commit.author,
                commits: context.payload.commits,
                hash: context.payload.head_commit.id,
                timestamp: context.payload.head_commit.timestamp,
            }

            const msTeamsCard = {
              "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
              "type": "AdaptiveCard",
              "version": "1.0",
              "body": [
                  {
                      "type": "Container",
                      "id": "fbcee869-2754-287d-bb37-145a4ccd750b",
                      "padding": "Default",
                      "spacing": "None",
                      "items": [
                          {
                              "type": "Container",
                              "id": "806fbac6-50ad-f79a-36a7-1f289cea6f7f",
                              "padding": "None",
                              "items": [
                                  {
                                      "type": "ColumnSet",
                                      "columns": [
                                          {
                                              "type": "Column",
                                              "id": "c8938dae-e2af-d15b-b7b5-67f46ad75e04",
                                              "padding": "None",
                                              "width": "auto",
                                              "items": [
                                                  {
                                                      "type": "Container",
                                                      "id": "9e75f7d3-aae4-d334-c521-12be272175d6",
                                                      "padding": "None",
                                                      "items": [
                                                          {
                                                              "type": "ColumnSet",
                                                              "columns": [
                                                                  {
                                                                      "type": "Column",
                                                                      "id": "b3e2ca55-fd5c-621b-8bfa-a7c979d90d71",
                                                                      "padding": "None",
                                                                      "width": "auto",
                                                                      "items": [
                                                                          {
                                                                              "type": "Image",
                                                                              "id": "e27467f5-b91b-f874-1156-cbfe979096d9",
                                                                              "url": "https://cdn0.iconfinder.com/data/icons/phosphor-fill-vol-3/256/git-merge-fill-35.png",
                                                                              "size": "Small",
                                                                              "width": "20px",
                                                                              "height": "20px"
                                                                          }
                                                                      ]
                                                                  },
                                                                  {
                                                                      "type": "Column",
                                                                      "id": "bd8c3006-2580-fbb8-ad49-944cc2c0e380",
                                                                      "padding": {
                                                                          "top": "None",
                                                                          "bottom": "None",
                                                                          "left": "Small",
                                                                          "right": "None"
                                                                      },
                                                                      "width": "auto",
                                                                      "items": [
                                                                          {
                                                                              "type": "TextBlock",
                                                                              "id": "cb69c3e0-9733-d468-32de-72e6cdf547a9",
                                                                              "text": "Merged",
                                                                              "wrap": true,
                                                                              "weight": "Bolder",
                                                                              "spacing": "None"
                                                                          }
                                                                      ],
                                                                      "spacing": "None"
                                                                  }
                                                              ],
                                                              "padding": "None"
                                                          }
                                                      ]
                                                  }
                                              ]
                                          }
                                      ],
                                      "padding": "None",
                                      "horizontalAlignment": "Right"
                                  },
                                  {
                                      "type": "TextBlock",
                                      "id": "44906797-222f-9fe2-0b7a-e3ee21c6e380",
                                      "text": info.title,
                                      "weight": "Bolder",
                                      "size": "Large",
                                      "wrap": true,
                                      "color": "Accent",
                                      "spacing": "None"
                                  },
                                  {
                                      "type": "ColumnSet",
                                      "columns": [
                                          {
                                              "type": "Column",
                                              "id": "d98c4e5d-0a53-9c19-96ed-5124381ddf6c",
                                              "padding": "None",
                                              "width": "auto",
                                              "items": [
                                                  {
                                                      "type": "TextBlock",
                                                      "id": "9a157b64-fb1f-b146-9964-70cd5ddf3cb3",
                                                      "text": `[${info.hash.substring(0, 7)}](${info.prUrl})`,
                                                      "wrap": true
                                                  }
                                              ]
                                          },
                                          {
                                              "type": "Column",
                                              "id": "7d88f63e-61de-7c0e-af6b-d3ed116cdbe5",
                                              "padding": {
                                                  "top": "None",
                                                  "bottom": "None",
                                                  "left": "Small",
                                                  "right": "Small"
                                              },
                                              "width": "auto",
                                              "items": [
                                                  {
                                                      "type": "Image",
                                                      "id": "d3bcd8f5-1620-dc4b-4f60-f4ce4309267d",
                                                      "url": "https://cdn0.iconfinder.com/data/icons/mobile-basic-vol-1/32/Arrow_Right-30.png",
                                                      "width": "20px",
                                                      "horizontalAlignment": "Center",
                                                      "size": "Stretch",
                                                      "spacing": "None",
                                                      "height": "20px"
                                                  }
                                              ],
                                              "spacing": "None"
                                          },
                                          {
                                              "type": "Column",
                                              "items": [
                                                  {
                                                      "type": "TextBlock",
                                                      "id": "df189bd7-6dad-99ea-4021-ac9b8ef69624",
                                                      "text": "**master**",
                                                      "wrap": true
                                                  }
                                              ],
                                              "padding": "None",
                                              "width": "auto",
                                              "spacing": "None"
                                          }
                                      ],
                                      "padding": "None",
                                      "spacing": "Small"
                                  }
                              ],
                              "style": "default",
                              "separator": true
                          },
                          {
                              "type": "Container",
                              "id": "4f98e073-5295-7248-ddfa-9d64d59b3e03",
                              "padding": "None",
                              "items": [
                                  {
                                      "type": "TextBlock",
                                      "id": "f7abdf1a-3cce-2159-28ef-f2f362ec937e",
                                      "text": info.message,
                                      "wrap": true
                                  }
                              ],
                              "separator": true,
                              "spacing": "Large"
                          },
                          {
                              "type": "ActionSet",
                              "id": "c8a5ba7e-7ec6-53ae-79da-0cfb952a527e",
                              "actions": [
                                  {
                                      "type": "Action.OpenUrl",
                                      "id": "9b98430f-c858-0317-d415-48e258f98472",
                                      "title": "Preview Changes",
                                      "url": info.previewUrl,
                                      "style": "positive",
                                      "isPrimary": true
                                  }
                              ],
                              "separator": true,
                              "spacing": "Large"
                          }
                      ]
                  }
              ],
              "padding": "None"
            }


            const msTeamsCardPayload = {
              "type":"message",
              "attachments":[
                  {
                    "contentType":"application/vnd.microsoft.card.adaptive",
                    "contentUrl":null,
                    "content": msTeamsCard
                  }
              ]
            }


            core.setOutput('msTeamsCard',JSON.stringify(msTeamsCardPayload))
            console.log(info,msTeamsCard)
        id: script
      - run: >-
          curl -H 'Content-Type: application/json' -d '${{steps.script.outputs.msTeamsCard}}' ${{ secrets.ms_teams_webhook }}
