name: "MsTeams Notifier Direct"

on:
  push:
    branches: [main]

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install axios
      - uses: actions/github-script@v6
        with:
          id: script
          script: |
            const getRelatedPr = await github.rest.repos.listPullRequestsAssociatedWithCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: process.env.GITHUB_SHA
             })

            const prNumber = getRelatedPr.data.length > 0 ? getRelatedPr.data[0].number : undefined;
            if (prNumber === undefined) {
              console.log("No matching PR number")
              exit(1)
            }
            const [title, message] = context.payload.head_commit.message.split("\n")

            const info = {
                prNumber,
                prUrl: getRelatedPr.data[0]._links.html.href,
                title,
                message,
                previewUrl: `https://deploy-preview-${prNumber}--airup-webshop-dev1.netlify.app`,
                commitUrl: context.payload.head_commit.url,
                pusher: context.payload.pusher.name,
                author: context.payload.head_commit.author,
                commits: context.payload.commits,
                hash: context.payload.head_commit.id,
                timestamp: context.payload.head_commit.timestamp,
            }

            const msTeamsCard = {
              "@type": "MessageCard",
              "@context": "https: //schema.org/extensions",
              themeColor: "0078D7",
              summary: "notificationSummary",
              title: info.title,
              sections: [
                {
                  activityTitle: info.author,
                  activityImage: "avatar_url",
                  activitySubtitle: "sdf",
                },
              ],
              potentialAction: [
                {
                  "@context": "http: //schema.org",
                  target: "ssdfsdfs",
                  "@type": "ViewAction",
                  name: "View Workflow Run",
                },
                {
                  "@context": "http: //schema.org",
                  target: "[commit.data.html_url]",
                  "@type": "ViewAction",
                  name: "View Commit Changes",
                },
              ],
            };

            core.setOutput('msTeamsCard',msTeamsCard)
            console.log(info,msTeamsCard)

      # Gets the output from the script and dose a curl req to the hook
      - run: >-
          curl -H 'Content-Type: application/json' -d '${{steps.script.outputs.msTeamsCard}}}' ${{ secrets.test_hook }}
