name: MS Teams WebHook

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Run a one-line script

        # Variables
        env:
          # Repository
          repositoryName: ${{ github.event.repository.name }}
          repositoryURL: ${{ github.event.repository.html_url }}
          # Author
          authorName: "zak"
          committerName: ${{ github.event.head_commit.committer.name }}
          authorUrl: ${{ github.event.author.html_url }}
          authorAvatarUrl: ${{ github.event.author.avatar_url }}
          # Commit
          commitMsg: ${{ github.event.head_commit.message }}
          commitUrl: ${{github.event.head_commit.html_url}}
          # Event
          eventType: ${{github.event.type}}
          eventUrl: ${{github.event.html_url}}

          msTeamsCard: '{
            "@type": "MessageCard",
            "@context": "https: //schema.org/extensions",
            "themeColor": "0078D7",
            "summary": "notificationSummary",
            "title": $commitMsg,
            "sections":
              [
                {
                  "activityTitle": $authorName,
                  "activityImage": "avatar_url",
                  "activitySubtitle": "sdf"
                }
              ],
            "potentialAction":
              [
                {
                  "@context": "http: //schema.org",
                  "target": "test",
                  "@type": "ViewAction",
                  "name": "View Workflow Run"
                },
                {
                  "@context": "http: //schema.org",
                  "target": "[commit.data.html_url]",
                  "@type": "ViewAction",
                  "name": "View Commit Changes"
                }
              ]
          }'

        run: >-
          curl -H 'Content-Type: application/json' -d '${{ env.msTeamsCard }}' ${{ secrets.test_hook }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo ${{ github.event }},
          echo test, and deploy your project.
